### PR TITLE
Load constituencies geo json

### LINKED ISSUE #56: Show constituency polygons on the map
This might be a tricky one. I think the client will need to request the GeoJSON file from the server and then probably the Mapbox GL JS package we're using has some built in functionality to render GeoJSON as a layer.

Could also add a convenience function to the data loading script to automatically fetch and save the GeoJSON file for us instead of manually retrieving it like currently specified.

### PR DESCRIPTION
**Pull request by jonleesy**
closes #56

### CODE REVIEW

**Comment by jonleesy** [comment]
image
Here's a screenshot. Not sure if results could be seen without mongo

**Comment by jonleesy** [comment]
image
Map now shows constituency name. Still not able to search for them yet

**Review by kymckay — APPROVED** [review]
Nice one! Good shout on just loading it straight from the source.

Any idea if there's a way to colour the individual areas differently? Not something that has to be done in this PR, but worth knowing.

**Comment by jonleesy** [comment]
> Nice one! Good shout on just loading it straight from the source.
> 
> Any idea if there's a way to colour the individual areas differently? Not something that has to be done in this PR, but worth knowing.

I've tried doing it individually and its possible I think. Just need to call a function that looks up the colour, something like `getColourFunc(['get', 'pcon19nm'])`

**Comment by jonleesy** [comment]
@kymckay I'm going to merge this first. Then try to see what could be done with colours. As well as showing some form of select upon hover

**Pull request merged**
