### PR TITLE
Add a disclaimer 

### LINKED ISSUE #57: Add disclaimer text under graph
We should really add a disclaimer that the prediction data is not real and only intends to demonstrate functionality (so it doesn't look like we're claiming they're real numbers from those sources).

### PR DESCRIPTION
**Pull request by linarietuma**
A disclaimer has been added to the info tooltip.
Also increased the z-index of the tooltip to stop map's search bar from appearing over it.
Closes #57

### CODE REVIEW

**Comment by kymckay** [comment]
My only concern with having it in the tooltip is that it's then hidden behind a layer of interaction and could still be misleading

**Comment by kymckay** [comment]
What about in the footer section with the other attributions?

**Comment by linarietuma** [comment]
That was my other thought but I don't think it fixes the issue of it possibly being misleading unless we make the footer big enough to make it obvious (would look weird). I guess my reasoning was that unless we make the disclaimer blatantly obvious (by placing it near the prediction data dropdown which I assume we don't want to do) it's not as important were it's placed as long as it's there (which already shows that we've thought about it). That said I don't have a strong preference so happy to move the disclaimer to the footer if you think that would be better?

**Comment by kymckay** [comment]
I think the footer will need to become a bit bigger anyway to fit a few lines of attribution so would probably go with that.

If you wanted to add the attribution at the same time check out the readme.md file in `data/` for details of what we'll need to have

**Comment by linarietuma** [comment]
That's disclaimer moved to footer and data attribution added.

**Review by kymckay — APPROVED** [review]
I might tweak the attribution text a bit later, but this seems good

**Pull request merged**
