### PR TITLE
Load constituencies geo json

### LINKED ISSUE #56: Show constituency polygons on the map
This might be a tricky one. I think the client will need to request the GeoJSON file from the server and then probably the Mapbox GL JS package we're using has some built in functionality to render GeoJSON as a layer.

Could also add a convenience function to the data loading script to automatically fetch and save the GeoJSON file for us instead of manually retrieving it like currently specified.

### PR DESCRIPTION
**Pull request by jonleesy**
Not ready, but PR just for review

closes #56

### CODE REVIEW

**Comment by kymckay** [comment]
@jonleesy I think you can avoid all of this and just serve the GeoJSON file from the server directly (it never need to enter the database)

**Comment by jonleesy** [comment]
Ahh, means like, could load it straight onto the map on load of the webpage?

**Comment by jonleesy** [comment]
@kymckay I think I am stuck again. Would be nice if you could take a look, I've pushed the latest. Managed to add single polygons but somehow can't get a loop to add them all.

**Comment by kymckay** [comment]
@jonleesy You can't read the file on the client-side like that for two reasons:
1. Node.js doesn't exist client-side
2. The file doesn't exist client side

You need to set up a request to the server asking for the file, then set up the server to serve the file (where it exists) upon request, then take the response and put _that_ into the map 😃

**Pull request closed without merging**
